bar {
	id bar-0
	font pango:JetBrains Mono Nerd Font 12
	position top
	status_command i3blocks
	i3bar_command i3bar --transparency
	padding 0px 2px 0px 2px
	strip_workspace_numbers yes
	colors {
        background #192330cc
		focused_workspace #9d79d6 #baa1e2 #393b44
		inactive_workspace #738091 #2b3b51 #dfdfe0
		urgent_workspace #dbc074 #e0c989 #393b44
		statusline #ffffff
	}
}
