#!/usr/bin/env sh
# Copyright (C) 2014 Julien Bonjean <julien@bonjean.info>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

TYPE="${BLOCK_INSTANCE:-mem}"
PERCENT="${PERCENT:-true}"

awk -v type=$TYPE -v percent=$PERCENT '
/^MemTotal:/ {
	mem_total=$2
}
/^MemFree:/ {
	mem_free=$2
	# mem_FREE=$2
}
/^Buffers:/ {
	mem_free+=$2
}
/^Cached:/ {
	mem_free+=$2
}
END {
	free=mem_free/1024/1024
	# FREE=mem_FREE/1024/1024
	used=(mem_total-mem_free)/1024/1024
	# USED=(mem_total-mem_FREE)/1024/1024
	total=mem_total/1024/1024
	
	pct=0
	if (total > 0) {
		pct=used/total*100
	}

	# full text
	printf("%.1fG / %.1fG (%.f%%)\n", used, total, pct)
	# short text
	printf("%.f%%\n", pct)

	# color
	if (pct > 90) {
		print(ENVIRON["color3"])
	} else if (pct > 70) {
		print(ENVIRON["color2"])
	}
}
' /proc/meminfo
