#!/bin/bash
#
# Copyright 2025 Jirou Hayashi <hayashi.jiro@kitsugo.com>
# Licensed under the terms of the GNU GPL v3, or any later version.

case "$BLOCK_BUTTON" in
1) wpctl set-mute @DEFAULT_SOURCE@ toggle ;;
3)
	dunstify "Microphone" "$(wpctl get-volume @DEFAULT_SOURCE@)\n<b>PulseAudio Default Source:</b>\n$(pactl get-default-source)\n<b>PipeWire Default Source Description:</b>\n$(wpctl inspect @DEFAULT_SOURCE@ | grep -oP 'node.description = \K.*')"
	;;
4)
	wpctl set-volume @DEFAULT_SOURCE@ 0.01+
	pkill --signal SIGRTMIN+10 i3blocks
	;;
5)
	wpctl set-volume @DEFAULT_SOURCE@ 0.01-
	pkill --signal SIGRTMIN+10 i3blocks
	;;
esac

if [[ "$(wpctl get-volume @DEFAULT_SOURCE@)" == *"MUTED"* ]]; then
	printf " 󰍭 \n"
else
	printf " 󰍬 \n"
fi
