#!/bin/sh
# Copyright 2024 Jirou Hayashi <hayashi.jirou@kitsugo.dev>
# Licensed under the terms of the GNU GPL v3, or any later version.
#
# Get current mediaplayer (playerctl) info
icon=$([ "$(playerctl --player=mpd,mpv status)" = "Playing" ] && echo "󰐊" || echo "󰏤")
title=$(playerctl --player=mpd,mpv metadata title || basename "$(playerctl --player=mpd metadata xesam:url)")
playerctl --player=mpd,mpv metadata --format "$icon ${title%%.mp3} {{ duration(position) }}/{{ duration(mpris:length) }}" | sed 's_&_&amp;_g; s_<_&lt;_g; s_>_&gt;_g;'
