#!/usr/bin/env sh
# Copyright 2024 Jirou Hayashi <hayashi.jiro@kitsugo.com>
# Licensed under the terms of the GNU GPL v3, or any later version.
#
# Print the current timewarrior activity
activity=$(timew export now | jq '.[0] | ."tags" | join(",")' 2>/dev/null) || exit 0
printf "%s\n" "$activity"
