#!/bin/bash
#
# Copyright 2025 Jirou Hayashi <hayashi.jiro@kitsugo.com>
# Licensed under the terms of the GNU GPL v3, or any later version.

case "$BLOCK_BUTTON" in
1)
	wpctl set-mute @DEFAULT_SINK@ toggle
	;;
3)
	dunstify "Volume" "$(wpctl get-volume @DEFAULT_SINK@)\n<b>PulseAudio Default Sink:</b>\n$(pactl get-default-sink)\n<b>PipeWire Default Source Description:</b>\n$(wpctl inspect @DEFAULT_SINK@ | grep -oP 'node.description = \K.*')"
	;;
4)
	wpctl set-volume @DEFAULT_SINK@ 0.01+
	;;
5)
	exit 0
	;;
esac

raw_volume=$(wpctl get-volume @DEFAULT_SINK@)
volume=${raw_volume##*: }
volume=${volume%% *}
volume_int=${volume/./}
volume_int=${volume_int#"${volume_int%%[!0]*}"}
if [[ "$raw_volume" == *"MUTED"* ]]; then
	printf ' 󰸈 %s\n' "$volume_int"
else
	if [[ $volume_int -ge 60 ]]; then
		printf ' 󰕾 %s%%\n' "$volume_int"
	elif [[ $volume_int -ge 30 ]]; then
		printf ' 󰖀 %s%%\n' "$volume_int"
	elif [[ $volume_int -ge 0 ]]; then
		printf ' 󰕿 %s%%\n' "$volume_int"
	fi
fi
