music_directory	"~/music/"
playlist_directory "/tmp/mpd/"
db_file "~/.local/share/mpd"
log_file "/tmp/mpd/log"

audio_output {
        type            "pipewire"
        name            "PipeWire Sound Server"
}

bind_to_address		"127.0.0.1"
port				"6600"
